# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Zetara' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Zetara
  pod 'RxBluetoothKit', '~> 6.0.0'

end
